### PR TITLE
Make a parallel cheta package alongside Ska.engarchive

### PR DESCRIPTION
**Pull request by taldcroft**
This is basically a re-do of #65 but with a better name and a cleaner implementation.  I *think* that this is all just fine and dandy, and basically installs two packages for the price of one.  There is no requirement I know of that a single "source" package (pip or conda) cannot install files that Python ends up viewing as two separate packages.

With the current conda build command that supplies `--egg` this is actually not an issue at all since they wind up in a distinct `Ska.engarchive-<version>/` directory anyway.  Even without `--egg` I still don't think conda really cares where the files wind up with respect to Python package architecture.

Along the way I cleaned some cruft in setup.py that I think is no longer (or was never) necessary.

Testing:
- Installed to a test Ska3 environment on HEAD (which is otherwise ska3-flight) using: `pip install --no-deps --verbose --no-binary :all: --no-index --egg`.
- From ipython on kadi ran:
```
import cheta
cheta.test('-v')
import Ska.engarchive
Ska.engarchive.test('v')
```
- No failures.

### CODE REVIEW

**Comment by taldcroft** [comment]
And one other thing that would need testing is building on Windows.

**Comment by taldcroft** [comment]
This is subsumed into #157 because testing on Windows is enough of a pain that I just want to do it for both `cheta` and `setuptools_scm` at once, and there is interaction there.

**Comment by taldcroft** [comment]
Sounds like a bug in GitHub.

**Comment by jeanconn** [comment]
Eh.  I've reviewed it now and it isn't in my list.

**Pull request closed without merging**
