### PR TITLE
Add LICENSE and license comments

### PR DESCRIPTION
**Pull request by taldcroft**
@jeanconn - I'm planning to do this kind of change for all the Ska packages in skare/cfg/python_modules.cfg.  Add LICENSE.rst and put the license text in every `.py` file.  The text is always after existing comment lines starting with `#` in the file.  Do you see any problems?

```
tables3_api
ska_path
parse_cm
Chandra.Time
Chandra.ECF
Ska.arc5gl
Ska.astro
Ska.engarchive
Ska.File
Ska.ftp
Ska.Shell
Ska.Numpy
Ska.CIAO
Ska.DBI
Ska.Table
Ska.ParseCM
Ska.Matplotlib
Ska.tdb
Ska.TelemArchive
cosmocalc
Quaternion
Ska.quatutil
Ska.Sun
Chandra.Maneuver
Chandra.cmd_states
kadi
agasc
pyyaks
asciitable
pyger
Chandra.taco
Ska.report_ranges
xija
chandra_aca
chandra_models
find_attitude
mica
hopper
maude
cxotime
starcheck
testr
```

### CODE REVIEW

**Comment by taldcroft** [comment]
BTW the funniness in `derived/pcad.py` is because of a leading `<U+FEFF>` in the file that Amanda left there.

**Comment by jeanconn** [comment]
The only potential problem I note is conflict with pre-existing text.  I know we have a license in the top of Quaternion.py.

**Comment by taldcroft** [comment]
Good point, I will do some grepping to look for existing licenses.

**Comment by jeanconn** [comment]
I also note that Ska.Sun may need a BSD-2 to agree with IDL astro for the sun position stuff (right now there is just a URL mentioning the source).

https://idlastro.gsfc.nasa.gov/idlfaq.html

**Pull request merged**
