### PR TITLE
Fix remote data access for Ska3

### LINKED ISSUE #150: Remote access fails due to returned vals, bads not owning data
[EDIT] See [non-copying-sends-and-numpy-arrays](https://ipyparallel.readthedocs.io/en/latest/details.html#non-copying-sends-and-numpy-arrays) for the explanation.

For reasons as yet unknown, in Ska.engarchive on Ska3 (version 3.44), the remotely fetched HDF5 data `vals` and `bads` come back not owning their data:
```
> /Users/aldcroft/miniconda3/envs/ska3/lib/python3.6/site-packages/Ska.engarchive-4.44-py3.6.egg/Ska/engarchive/fetch.py(765)_get_msid_data_from_cxc()
    763 
    764         vals, bads = get_msid_data_from_server(h5_slice, _split_path(filename))
--> 765         bads.flags['WRITEABLE'] = True  # Remote access can return a readonly bads
    766 
    767         # Filter bad times rows if needed

ipdb> bads.base
array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)
ipdb> len(bads.base)
9856
ipdb> len(bads)
9856
ipdb> type(bads.base)
<class 'numpy.ndarray'>
ipdb> type(bads)
<class 'numpy.ndarray'>
ipdb> vals.base
array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)
ipdb> vals.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False
ipdb> filename
'/proj/sot/ska/data/eng_archive/data/ccdm15eng/DWELL01.h5'
ipdb> h5_slice
slice(7424, 17280, None)
```
I don't understand why this is happening now, but presumably related to newer versions of packages behaving differently.  It also generally makes no sense since I confirmed that when the following is run locally that `vals` and `bads` are just plain ndarrays that have no `base` and own data and are writeable (i.e. they are not a slice).  So why they come back through Ipython parallel differently is a mystery.  
```
        @local_or_remote_function("Getting msid data for " + msid +
                                  " from Ska eng archive server...")
        def get_msid_data_from_server(h5_slice, filename):
            import tables
            open_file = getattr(tables, 'open_file', None) or tables.openFile
            h5 = open_file(os.path.join(*filename))
            vals = h5.root.data[h5_slice]
            bads = h5.root.quality[h5_slice]
            h5.close()
            return(vals, bads)
```
Barring understanding, there is a simple workaround to just make copies of `vals` and `bads` if necessary.

### PR DESCRIPTION
**Pull request by taldcroft**
Fixes #150 

As a reminder, the appropriate ska_remote_access.json file needs to be in place.

## Testing (from git repo)
```
(ska3) neptune$ ska_version
2018.12.18-f55b6df
(ska3) neptune$ export ENG_ARCHIVE=/proj/sot/ska/data/eng_archive
(ska3) neptune$ ipython
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: >>> import Ska.engarchive.remote_access
   ...: >>> Ska.engarchive.remote_access.access_remotely = True
   ...: >>> import Ska.engarchive.fetch_eng as fetch
   ...: 
Enter hostname (or IP) of Ska server (enter to cancel):131.142.xxx
Enter your login username [aldcroft]:SOT
Enter your password:
Establishing connection to 131.142.xxx...
fetch: using ENG_ARCHIVE=/proj/sot/ska/data/eng_archive for archive path

In [2]: from Ska.engarchive.tests.test_fetch import test_ctu_dwell_telem
/Users/aldcroft/git/eng_archive/Ska/engarchive/fetch.py

In [3]: test_ctu_dwell_telem()

In [4]: import Ska.engarchive

In [5]: Ska.engarchive.test()
========================================================================= test session starts =========================================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/aldcroft/git/eng_archive, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 66 items                                                                                                                                                     

Ska/engarchive/tests/test_data_source.py .........
Ska/engarchive/tests/test_fetch.py .....................
Ska/engarchive/tests/test_fetch_regr.py s
Ska/engarchive/tests/test_intervals.py ..........
Ska/engarchive/tests/test_orbit.py .
Ska/engarchive/tests/test_units.py ...........
Ska/engarchive/tests/test_units_reversed.py ...........
Ska/engarchive/tests/test_utils.py ..

================================================================ 65 passed, 1 skipped in 84.00 seconds ================================================================
```

### CODE REVIEW

**Comment by mbaski** [comment]
This resolves the issue on Windows (successfully tested both in MCC and standalone iPython). However I'm seeing another issue - when retrieving a state code MSID (AOFATTMD), raw_vals is "None" even though vals is not empty.

**Comment by taldcroft** [comment]
> However I'm seeing another issue - when retrieving a state code MSID (AOFATTMD), raw_vals is "None" even though vals is not empty.

Looking at this now...  I see for a straight fetch using Ska3 on HEAD linux that it works as expected.

**Comment by mbaski** [comment]
I'm actually seeing the same thing in Python 2 (the MATLAB Tools code keeps going in the flight version but breaks in the latest testing version, which I need to fix).  Maybe it is something specific to the time range I'm requesting or perhaps with remote access.  I'll try to isolate it further.

**Comment by taldcroft** [comment]
I'm not reproducing this on my mac. Can you try this:
```
In [1]: >>> import Ska.engarchive.remote_access
   ...: >>> Ska.engarchive.remote_access.access_remotely = True
   ...: >>> import Ska.engarchive.fetch_eng as fetch
   ...: 
Enter hostname (or IP) of Ska server (enter to cancel):131.142...
Enter your login username [aldcroft]:SOT
Enter your password:
Establishing connection to 131.142...
fetch: using ENG_ARCHIVE=/proj/sot/ska/data/eng_archive for archive path

In [2]: dat = fetch.Msid('aofattmd', '2018:001', '2018:002')

In [3]: dat.vals
Out[3]: 
array(['MNVR', 'MNVR', 'MNVR', ..., 'MNVR', 'MNVR', 'MNVR'], 
      dtype='<U4')

In [4]: dat.raw_vals
Out[4]: array([1, 1, 1, ..., 1, 1, 1], dtype=int8)
```

**Comment by taldcroft** [comment]
@mbaski - the state codes machinery depends on data in $SKA/data/Ska.tdb/p* (e.g. p014).  Do you have that installed?

**Comment by taldcroft** [comment]
And this data is currently **local**, not fetched remotely.

**Comment by taldcroft** [comment]
I can reproduce getting `None` for `raw_vals` if the Ska.tdb data are not available locally.

**Comment by mbaski** [comment]
That must be it.  Currently I can't rely on on Ska data being available on a user's PC, so I'll fix the MATLAB Tools code to continue on if it encounters this situation, same as it did before (I don't want to implement a more major change this late in the release cycle to fix it properly).

**Comment by taldcroft** [comment]
I personally find `Ska.tdb` to be super useful.  Other users' mileage may vary... but at least the syncing only occurs for each update to the TDB.

Otherwise, this appears to work.  I'm a bit hesitant to introduce this as a late point as a "bug fix", but could be convinced.
```
        @local_or_remote_function("Getting state codes for {} from server".format(self.MSID))
        def get_state_codes_from_server(msid):
            import numpy as np
            import Ska.tdb
            try:
                states = Ska.tdb.msids[msid].Tsc
            except Exception:
                state_codes = None
            else:
                if states is None or len(set(states['CALIBRATION_SET_NUM'])) != 1:
                    warnings.warn('MSID {} has string vals but no state codes '
                                  'or multiple calibration sets'.format(msid))
                    state_codes = None
                else:
                    states = np.sort(states.data, order='LOW_RAW_COUNT')
                    state_codes = [(state['LOW_RAW_COUNT'], state['STATE_CODE'])
                                   for state in states]
            return state_codes

        if not hasattr(self, '_state_codes'):
            self._state_codes = get_state_codes_from_server(self.MSID)
```

**Comment by mbaski** [comment]
I have a bug fix ready in the MATLAB Tools code (actually, in the python interface code) to make the code behave the same as before (just waiting on a response from Steve regarding release status before committing it).

I've also added an optional sync at startup where Ska.tdb will get synced if it exists.  This makes it an easy fix for anyone that needs/wants it but avoids another sync check (which takes a few seconds at startup) for users that don't.

**Pull request merged**
